version: 2

sources:
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "BLAST_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "BLAST" }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: traces
      - name: decoded_logs
      - name: confirm_blocks
  - name: udfs_streamline
    database: udfs
    schema: streamline
    tables:
      - name: node_mapping
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'BLAST' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_labels
  - name: silver_crosschain
    database: crosschain_dev
    schema: silver
    tables:
      - name: apis_keys
      - name: near_address_encoded
      - name: labels_combined
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: blast_silver
    database: blast
    schema: silver
    tables:
      - name: verified_abis
  - name: blast_bronze_api
    database: blast
    schema: bronze_api
    tables:
      - name: contract_abis
  - name: github_actions
    database: blast
    schema: github_actions
    tables:
      - name: workflows
  - name: external_gold_defillama
    database: external
    schema: defillama
    tables:
      - name: dim_chains
